scraper:
  # input-folder: D:/Site/brain/itksnap-master
  # output-file: D:/Site/brain/itksnap-master.txt
  # input-folder: D:/synapses
  # output-file: D:/Site/apass/synapses.txt
  # input-folder: D:/Site/apass/task-manager-ai-hero/task-manager-backend
  # output-file: D:/Site/apass/task-manager-ai-hero/task-manager-backend.txt
  # input-folder: D:/Site/apass/task-manager
  # output-file: D:/Site/apass/task-manager-ai-hero-doc/task-manager.txt
  # input-folder: D:/Site/scraper
  # output-file: D:/Site/apass/scraper/scraper.txt
  input-folder: D:/Site/ai-finance-system
  output-file: D:/Site/apass/scraper/ai-finance-system.txt
  include-extensions:
    - java
    - c
    - cs
    - cpp
    - cxx
    - txx
    - hxx
    - sh
    - cc
    - shader
    - js
    - html
    - tcl
    - ts
    - tsx
    - py
    - xml
    - txt
    - json
    - md
    - yml
    - yaml
    - css
    - scss
    - html
    - conf
    - env
    - .env
    - .container
    - .env.container
    - prod
    - gitignore
    - h
    - m
    - mm
    - rtf
    - csproj
  exclude-folders:
    - build
    - Builds
    - Library
    - Logs
    - obj
    - Temp
    - UserSettings
    - Packages
    - target
    - bin
    - .git
    - .github
    - node_modules
    - .angular
    - .nx
    - .next
    - .idea
    - patches
    - .vscode
    - .vs
    - obj
    - .venv
    - venv
    - public
    - .mvn
    - data
    - plugins
    - png
    - pdf
    - csv
  exclude-file-patterns:
    - "*lock.json"
    - "yarn.lock"
    - "*.spec.ts"
    - "docker-compose.override.yml"
    - ".*.bak"
    - ".*.png"
    - "*.log"
    - "*.tmp"
  exclude-pattern-case-sensitive: false
  run-on-startup: true
